
#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - nginx
write_files:
  - content: |
      <html><img src="http://storage.yandexcloud.net/fedors-bucket/DevOps.png"></html>
    path: /var/www/html/index.html
    permissions: '0644'
